#!/bin/bash

# This script is only necessary because the jdaviz kernel has been eliminated,
# but for previous users, the jdaviz kernel configuration already exists

kernel_dir=/home/jovyan/.local/share/jupyter/kernels/jdaviz

if [ -d $kernel_dir ]; then
    rm -rf $kernel_dir
fi
