#! /bin/bash -eu

# This is a standard entry-point used to set up notebooks for this
# Docker image.   It is nominally used to pull notebook repos using
# nbgitpuller and then update the default kernels specified in the
# notebook files using set-notebook-kernels.

gitpuller https://github.com/spacetelescope/jwebbinar_prep current_webbinar jwebbinar_prep

#/opt/common-scripts/set-notebook-kernel jdaviz jdaviz jwebbinar_prep/test_environment/JWebbinar_viztool_tests.ipynb

#/opt/common-scripts/set-notebook-kernel jwebbinar JWebbinar jwebbinar_prep/test_environment/pipeline_testenv_nirissdata.ipynb

#/opt/common-scripts/set-notebook-kernel jwebbinar JWebbinar jwebbinar_prep/pipeline_products_session/*.ipynb

/opt/common-scripts/set-notebook-kernel jdaviz Jdaviz jwebbinar_prep/jdat_session/*.ipynb

# /opt/common-scripts/set-notebook-kernel jwebbinar JWebbinar jwebbinar_prep/imaging_mode/*.ipynb
