#! /bin/bash -eu

# ----------------- derived inputs, nominally don't change --------------
# automatically sourced into setup-env

# Octarine AWS JupyterHub setup
export ACCOUNT=${ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com

export JUPYTERHUB_DIR=`pwd`

export IMAGE_REPO=${DEPLOYMENT_NAME}-user-image
export COMMON_REPO=${IMAGE_REPO}

export ADMIN_ARN=arn:aws:iam::${ACCOUNT_ID}:role/${ADMIN_ROLENAME}

export COMMON_DIR=`pwd`/deployments/common/image
export IMAGE_DIR=`pwd`/deployments/${DEPLOYMENT_NAME}/image

if [[ "${PERSONAL_IMAGE}" == "0" ]]; then
    export COMMON_ID=${ACCOUNT}/${COMMON_REPO}:${COMMON_TAG}
    export IMAGE_ID=${ACCOUNT}/${IMAGE_REPO}:${IMAGE_TAG}
else
    export COMMON_ID=${COMMON_REPO}:${COMMON_TAG}
    export IMAGE_ID=${IMAGE_REPO}:${IMAGE_TAG}
fi

export PATH="`pwd`/tools":${PATH}

# --------------- general setup ---------------------------------

export TMOUT=7200
export TF_LOG=TRACE
export TF_LOG_PATH=terraform.log
