jupyterhub:
  scheduling:
    userPlaceholder:
      enabled: true
      replicas: 1
  singleuser:
    image:
      tag: latest-dev
    storage:
      extraVolumes:
        - name: systats
          persistentVolumeClaim:
            claimName: task-pv-claim
      extraVolumeMounts:
        - name: systats
          mountPath: /sysstats
          readOnly: true
  prePuller:
    continuous:
      enabled: true
