jupyterhub:
  scheduling:
    userPlaceholder:
      enabled: true
      replicas: 1
  singleuser:
    image:
      tag: latest-dev
    storage:
      extraVolumes:
        - name: dshm
          emptyDir:
            medium: Memory
      extraVolumeMounts:
        - name: dshm
          mountPath: /dev/shm
  prePuller:
    continuous:
      enabled: true

