jupyterhub:
  scheduling:
    userPlaceholder:
      enabled: true
      replicas: 1
  singleuser:
    image:
      tag: latest-dev
    storage:
      extraVolumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: s3-pvc
          persistentVolumeClaim:
            claimName: s3-pvc
        - name: systats
          persistentVolumeClaim:
            claimName: task-pv-claim
      extraVolumeMounts:
        - name: dshm
          mountPath: /dev/shm
        - name: s3-pvc
          mountPath: /s3
        - name: systats
          mountPath: /sysstats
          readOnly: true
  prePuller:
    continuous:
      enabled: true
