apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: s3-goofys-{{ .Values.bucketName }}
  name: s3-goofys-{{ .Values.bucketName }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels: 
      app: s3-goofys-{{ .Values.bucketName }}
  template:
    metadata:
      labels:
        app: s3-goofys-{{ .Values.bucketName }}
    spec:
      containers:
      - name: s3-goofys-{{ .Values.bucketName }} 
        image: {{ .Values.image.repository }}:{{ .Values.image.tag}}
        command: ["./goofys", "-f", "--dir-mode", "0555", "--file-mode",  "0444",
                  "-o", "ro,allow_other,noatime,noexec",
                  "{{ .Values.bucketName }}", "/s3/gf/{{ .Values.bucketName}}"]
        lifecycle:
          preStop:
            exec:
              command: ["umount", "/s3/gf/{{ .Values.bucketName}}"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: mntdatas3
          mountPath: "/s3/gf/{{ .Values.bucketName}}:shared"
        env:
          - name: S3_BUCKET
            value: {{ .Values.bucketName }}
          - name: MOUNT_PATH
            value: "/s3/gf/{{ .Values.bucketName}}"
      volumes:
      - name: mntdatas3
        hostPath:
          path: "/s3/gf/{{ .Values.bucketName}}"
