apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3
  labels:
    type: local
spec:
  storageClassName: local-storage
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 1M
  storage:
  hostPath:
    path: /s3
