apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-pvc
  labels:
    type: s3
spec:
  storageClassName: local-storage
  selector:
    matchLabels:
      type: s3
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1M
