{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm.serviceAccountName" . }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.iamRoleARN }}
{{- end -}}
