#! /bin/sh -eux

if [[ ! -f tls-ca-bundle.pem ]]; then
    cp -f /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem .
fi

if [[ ! -f ca-bundle.trust.crt ]]; then
    cp -f /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt .
fi

docker build --tag ${ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/${DEPLOYMENT_NAME}-user-image .

awsudo ${ADMIN_ARN} aws ecr get-login-password --region=us-east-1 | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com

docker push ${ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/${DEPLOYMENT_NAME}-user-image:latest

