#! /bin/bash -ux

# Each project should define a /opt/tests/test script satisfying:
# 1. Runs arbitrary commands each resulting in pass/fail.
# 2. Counts failures from multiple tests.
# 3. Returns zero for pass,  non-zero count for fail.
# 4. Fails intelligently, collecting as much info as possible w/o
#    running tests known to be doomed.

echo "Testing."

exit 0
