#!/usr/bin/bash
 
secret=$(aws secretsmanager get-secret-value --secret-id ${DD_API_KEY_SECRET} --region us-east-1 | grep 'SecretString' | awk -F: '{print $2}' | xargs | sed 's|["'\'']||g' | sed '
 s/,$//')

printf '{"api_key": {"value": "'
printf "${secret}"
printf '", "error": "" }}\n'
