#! /bin/bash

# Standardize how we install apt packages and cleanup after,  make it easy.
# 1. Install apt packages, without any questions asked
# 2. Update pacakge metadata before install
# 3. Remove unneeded files after install

if [ $# == 0 ];  then
echo "usage: apt-install <packages...>"
exit 0
fi

set -eu

PACKAGES=$*

apt-get update --yes && \
DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --yes ${PACKAGES} && \
apt-get clean && \
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
