#! /bin/bash

set -eu

# Skip this setup if buildkit caching is *not* being used.
mkdir -p /opt
chown -R $NB_UID:$NB_GID /opt

mkdir -p /home/jovyan/.cache
chown -R $NB_UID:$NB_GID /home/jovyan/.cache

mkdir -p /opt-conda-cache
chown $NB_UID:$NB_GID -R /opt-conda-cache

echo 'pkg_dirs: [ /opt-conda-cache ]' >/home/jovyan/.condarc
