#! /bin/bash

# This script replaces Ubuntu certs and sets environment variables and needs to be called
# after every apt install or upgrade remediating possible cert updates which undo this
# STScI cert install.

set -eu

ln -fs /etc/ssl/certs/stsci-tls-ca-bundle.pem  /etc/ssl/certs/ca-bundle.crt

ln -fs /etc/ssl/certs/stsci-tls-ca-bundle.pem /etc/ssl/certs/tls-ca-bundle.pem

ln -fs /etc/ssl/certs/stsci-tls-ca-bundle.pem  /etc/ssl/certs/ca-certificates.crt

ln -fs /etc/ssl/certs/stsci-tls-ca-bundle.pem  /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem

# mv /usr/lib/ssl/cert.pem  /usr/lib/ssl/cert.pem.org
mkdir -p /usr/lib/ssl
ln -fs /etc/ssl/certs/stsci-tls-ca-bundle.pem /usr/lib/ssl/cert.pem

mkdir -p /etc/pki/ca-trust/extracted/openssl

npm config -g set cafile "/etc/ssl/certs/stsci-tls-ca-bundle.pem"

# Fix conda environments if any exist.
for cert in `find /opt/conda -name '*.pem'`;
do
    echo "Replacing $cert"
    ln -v -fs /etc/ssl/certs/stsci-tls-ca-bundle.pem  $cert
done
