#! /bin/bash

set -ex

# jupyter labextension install @jupyterlab/server-proxy && \

jupyter labextension install @jupyterlab/server-proxy @jupyter-widgets/jupyterlab-manager ipyevents jupyter-vuetify jupyter-golden-layout jupyter-splitpanes d3-selection-multi bqplot-image-gl && \
    jupyter nbextension enable --py --sys-prefix ipyevents && \
    jupyter nbextension install --py --sys-prefix widgetsnbextension && \
    jupyter nbextension enable --py --sys-prefix widgetsnbextension && \
    jupyter nbextension install --py --sys-prefix ipyevents && \
    jupyter nbextension enable --py --sys-prefix ipyevents && \
    jupyter nbextension install --py --sys-prefix ipyvuetify && \
    jupyter nbextension enable --py --sys-prefix ipyvuetify && \
    jupyter nbextension install --py --sys-prefix ipysplitpanes && \
    jupyter nbextension enable --py --sys-prefix ipysplitpanes && \
    jupyter nbextension install --py --sys-prefix bqplot && \
    jupyter nbextension enable --py --sys-prefix bqplot && \
    jupyter nbextension install --py --sys-prefix bqplot_image_gl && \
    jupyter nbextension enable --py --sys-prefix bqplot_image_gl

if [[ "${JH_DEVELOP}" == "" || "${JH_DEVELOP}" == "0" ]]; then
    jupyter lab build -y && \
    jupyter lab clean -y && \
    npm cache clean --force && \
    rm -rf "/home/${NB_USER}/.cache/yarn" && \
    rm -rf "/home/${NB_USER}/.node-gyp"
fi
