#! /bin/bash

set -eux

jupyter nbextension enable --py --sys-prefix  ipyvuetify
jupyter nbextension enable --py --sys-prefix  ipysplitpanes

npm install -g d3-selection-multi
npm install -g jupyter-splitpanes
npm install -g jupyter-golden-layout
npm install -g bqplot-image-gl

# Skip cache clearing if buildkit caching is enabled or dev-mode is enabled.
if [[ "${CLEAR_PKG_CACHES}" == "1" ]]; then
    # Clear the lab and npm caches
    echo "-------------------------------------------------------------------------------"
    echo "===== Clearing jupyterlab and npm caches"
    jupyter lab clean -y
    npm cache clean --force
    rm -rf "/home/${NB_USER}/.cache/yarn"
    rm -rf "/home/${NB_USER}/.node-gyp"
fi
