#! /usr/bin/env python
# -*-python-*-

"""Import the packages listed on the command line to test installation."""

import sys

if (len(sys.argv) < 2):
    print("test-imports <pkgs...>", file=sys.stderr)
    sys.exit(1)

import_list = sys.argv[1:]

errs = 0
for pkg in import_list:
    if pkg.startswith("#"):
        print("Skipping", pkg)
        continue
    try:
        __import__(pkg)
        print("Importing", pkg, "... ok")
    except ImportError:
        print("Importing", pkg, "... FAIL")
        errs += 1

sys.exit(errs)
