#! /usr/bin/env python

# This script is used to remove kernel specification
# for given Jupyter notebooks

# usage: unset-notebook-kernel <notebooks...>

import json
import argparse


def unset_set_kernel(notebook):
    kernelspec_found = False
    with open(notebook) as nb:
        loaded = json.loads(nb.read())
        if loaded.get("metadata", {}):
            if loaded["metadata"].get("kernelspec", {}):
                kernelspec_found = True
                loaded["metadata"].pop("kernelspec")

    if kernelspec_found:
        with open(notebook, "w+") as nb:
            nb.write(json.dumps(loaded, indent=1))


def parse_args():
    parser = argparse.ArgumentParser(
        description="Remove kernel specification from Jupyter notebooks"
    )
    parser.add_argument("notebooks", type=str, nargs="+", help="Notebooks to update")
    args = parser.parse_args()
    return args


def main():
    args = parse_args()
    for notebook in args.notebooks:
        unset_set_kernel(notebook)


if __name__ == "__main__":
    main()
