#! /bin/bash

# Ubuntu update script for patching images

apt-get update --yes &&
DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade --yes && \
apt-get clean && \
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
