#! /bin/bash -ex

cd ${JUPYTERHUB_DIR}/datadog

echo "========================= Deploying DataDog ========================"
helm install datadog datadog/datadog -f datadog.yaml \
    --set registry=${ECR_REGISTRY}/datadog \
    --create-namespace -n datadog
