#! /usr/bin/bash

deployment_name=$1
image_tag=$2
account_id=$3
secrets_yaml=$4
environment=$5

helm upgrade --wait --install --namespace ${deployment_name}-${environment} ${deployment_name}-${environment} hub -f deployments/${deployment_name}/config/common.yaml -f deployments/${deployment_name}/config/${environment}.yaml -f ${secrets_yaml} --set-string jupyterhub.singleuser.image.tag=${image_tag} --set-string jupyterhub.singleuser.image.name=${account_id}.dkr.ecr.us-east-1.amazonaws.com/${deployment_name}-user-image
