#! /bin/bash -e

cd $JUPYTERHUB_DIR

awsudo $ADMIN_ARN aws eks update-kubeconfig --name ${DEPLOYMENT_NAME} --region us-east-1 --role-arn arn:aws:iam::${ACCOUNT_ID}:role/jupyterhub-admin

tools/deploy ${DEPLOYMENT_NAME} ${ACCOUNT_ID} secrets/deployments/${DEPLOYMENT_NAME}/secrets/${ENVIRONMENT}.yaml ${ENVIRONMENT}

kubectl get svc proxy-public
