#! /bin/bash -eux

source ${JUPYTERHUB_DIR}/setup-env

awsudo $ADMIN_ARN aws eks update-kubeconfig --name ${DEPLOYMENT_NAME} --region us-east-1 --role-arn arn:aws:iam::${ACCOUNT_ID}:role/${DEPLOYMENT_NAME}-hubploy-eks

${JUPYTERHUB_DIR}/tools/deploy ${DEPLOYMENT_NAME} ${ACCOUNT_ID} secrets/deployments/${DEPLOYMENT_NAME}/secrets/${ENVIRONMENT}.yaml ${ENVIRONMENT}

kubectl get svc proxy-public
