#! /bin/bash -e

cd ${JUPYTERHUB_DIR}/datadog

echo "========================= Building DataDog Image ========================"
image-login

# build docker image from public registry
docker pull datadog/agent

# ...
docker build --progress plain --tag ${ECR_REGISTRY}/datadog:unscanned-latest-${ENVIRONMENT} .




