#!/usr/bin/env python

import os
import sys
import subprocess
import boto3


env = os.environ.get('ENVIRONMENT', None)
central_ecr_account_id = os.environ.get('CENTRAL_ECR_ACCOUNT_ID', None)
deployment_name = os.environ.get('DEPLOYMENT_NAME', None)

# TODO: make sure all these env vars are not None

digest = sys.argv[1]
tag = sys.argv[2]

ecr = boto3.client('ecr')

ecr.batch_delete_image(
    repositoryName=deployment_name,
    registryId=central_ecr_account_id,
    imageIds=[
        {
            'imageDigest': digest,
            'imageTag': tag
        }
    ]
)
