#!/usr/bin/env python

import os
import sys
import subprocess
import json

"""
The script is used to promote a docker image from either
    dev --> test
    test --> prod

To promote an image, we find an image in the central ECR that has a tag
of the pattern "latest-<dev | test>".  So, if $ENVIRONMENT=dev, we look for
"latest-dev", and then add a tag of "latest-test".  Doing so makes the image
available to the test cluster.
"""

print(str(sys.argv))

registry = str(sys.argv[1])
repo_name = str(sys.argv[2])
old_tag = str(sys.argv[3])
new_tag = str(sys.argv[4])


with open('./manifest.json', 'w') as json_file:
    stream = os.popen(f"awsudo $ADMIN_ARN aws ecr batch-get-image --registry-id {registry} --repository-name {repo_name} --image-ids imageTag={old_tag} --accepted-media-types string --output json --query 'images[0].imageManifest'")
    output = stream.read().replace("\\n","").replace("\\","").strip().strip("\"")
    manifest = json.loads(output)
    json.dump(manifest, json_file, indent=2)

cmd = f"awsudo $ADMIN_ARN aws ecr put-image --repository-name {repo_name} --image-manifest file://manifest.json --image-tag {new_tag} --registry-id {registry}"
stream = os.popen(cmd)
output = stream.read()
print(output)
