#! /bin/bash

cd $IMAGE_DIR

image-login

IMAGE_ID=${1:-`echo ${IMAGE_ID} | sed -e's/unscanned-//g'`}

echo "================================== Pulling ${IMAGE_ID} =============================="
docker image rm $IMAGE_ID
docker pull $IMAGE_ID
