#! /bin/bash

set -u

# pip-tools frozen requirements for use with USE_FROZEN=1 are stored at
# /opt/envs-frozen in the image.  Copy /opt/envs-frozen to env-frozen in the
# Docker sources mission dir.

cd $IMAGE_DIR

# Blow away old requirements in case any files were removed during this build
rm -rf env-chilly

# Chilly requirements are saved during compilation;  copy them out of the image, whatever they were
image-cp /opt/env-chilly

# Create simpler frozen diffs for debugging/monitoring chilly effects, remove incidental chilly copies
for env in  $(image-envs); do
    git diff env-frozen/${env}/requirements.txt  | grep -v '#' > env-frozen/${env}/requirements.diffs.txt
    rm -f env-chilly/${env}/requirements.diffs.txt
done



