#! /bin/bash -eu

# Log into AWS ECR based on the current shell environment.

awsudo ${ADMIN_ARN} aws ecr get-login-password --region=us-east-1 | docker login --username AWS --password-stdin ${ECR_REGISTRY}
