#! /bin/bash -e

cd ${JUPYTERHUB_DIR}/datadog

echo "========================= Building DataDog Image ========================"
image-login

docker pull datadog/agent

docker build --tag ${ECR_REGISTRY}/datadog:unscanned-latest-${ENVIRONMENT} \
       --build-arg DD_API_KEY_SECRET=${DD_API_KEY_SECRET} .
