#! /bin/bash

set -eu

echo "========================= Building Base Image ========================"

# These build-args are added to the image environment and will be available in
#   all subsequent builds based on this image.

cd ${JUPYTERHUB_DIR}/deployments/common/image
docker build --progress plain --tag stsci-jh/ubuntu-certs --file Dockerfile.certs.x \
       --build-arg USE_FROZEN=${USE_FROZEN} \
       --build-arg PIP_SWITCHES="${PIP_SWITCHES}" \
       --build-arg CLEAR_PKG_CACHES="${CLEAR_PKG_CACHES}" \
       --build-arg CONDA_VER=${CONDA_VER} \
       .

cd ~
if [[ ! -d docker-stacks ]]; then
   git clone https://github.com/jupyter/docker-stacks.git
fi
cd docker-stacks

DARGS="--build-arg ROOT_CONTAINER=stsci-jh/ubuntu-certs:latest" OWNER=stsci-jh make build/base-notebook

DARGS="--build-arg BASE_CONTAINER=stsci-jh/base-notebook:latest" OWNER=stsci-jh make build/minimal-notebook

DARGS="--build-arg BASE_CONTAINER=stsci-jh/minimal-notebook:latest" OWNER=stsci-jh make build/scipy-notebook
