#! /bin/bash -eu

echo "========================= Building Base Image ========================"

cd ${JUPYTERHUB_DIR}/deployments/common/image
docker build --tag ubuntu-certs --file Dockerfile.certs .

cd ~
if [[ ! -d docker-stacks ]]; then
   git clone https://github.com/jupyter/docker-stacks.git
fi
cd docker-stacks

DARGS="--build-arg ROOT_CONTAINER=ubuntu-certs:latest" make build/base-notebook

DARGS="--build-arg BASE_CONTAINER=jupyter/base-notebook:latest" make build/minimal-notebook

DARGS="--build-arg BASE_CONTAINER=jupyter/minimal-notebook:latest" make build/scipy-notebook
