#! /bin/bash

# This is for doing parallel builds of all deployments using buildkit
# Either buildkit must be supported by your version of Docker or
# the DOCKER_BUILDKIT=1 setting must be used.

set -eu

for USE_FROZEN in 0 1; do
    for DEPLOYMENT_NAME in jwebbinar roman tike; do
        id="build-${DEPLOYMENT_NAME}-${USE_FROZEN}"
        echo "============ Starting ${id}"
        cd ${JUPYTERHUB_DIR}
        image-configure ${DEPLOYMENT_NAME} ${USE_FROZEN}
        source setup-env
        # tags for tracking here only, not intended for push, not valid for e.g. running on hub
        export IMAGE_ID=${IMAGE_ID}-${USE_FROZEN}
        export COMMON_ID=${COMMON_ID}-${USE_FROZEN}
        if [[ `docker buildx ls | grep ${id}` == "1" ]];  then
            docker buildx create --use --name ${id}
        fi
        nohup image-build 2>&1 >${id}.log &
        sleep 5
    done
done
