#! /bin/bash -eu

# Log into the container registry and push the current image.

cd $IMAGE_DIR

image-login

# docker push ${COMMON_ID}

echo "================================== Pushing ${IMAGE_ID} =============================="
docker push ${IMAGE_ID}

if [[ ${IMAGE_WAIT_FOR_ECR_SCAN} == "1" ]]; then
    image-scan
fi
