#! /bin/bash -eux

image-update   # Make automatic source adjustments

cd ${COMMON_DIR}

# git rev-parse HEAD > common-image-git-hash
echo "========================= Building Common Image ========================"
# common image doesn't currently exploit frozen
time docker build --tag ${COMMON_ID} --build-arg USE_FROZEN=${USE_FROZEN}  .

cd ${IMAGE_DIR}

# git rev-parse HEAD > mission-image-git-hash

echo "========================= Building $IMAGE_ID USE_FROZEN=${USE_FROZEN} =========================="
time docker build --tag ${IMAGE_ID} --build-arg USE_FROZEN=${USE_FROZEN} --build-arg BASE_IMAGE=${COMMON_ID} .

if [[ "$USE_FROZEN" == "0" ]]; then
    echo "========================= Freezing Requirements =========================="
    time image-freeze
fi
