#! /bin/bash

set -eu

# pip-tools frozen requirements for use with USE_FROZEN=1 are stored at
# /opt/envs-frozen in the image.  Copy /opt/envs-frozen to env-frozen in the
# Docker sources mission dir.

cd $IMAGE_DIR

image-cp /opt/env-frozen

# fuzz out mission specific pip reqs only to create a build with less security issues
cp -r env-frozen env-chilly
sed -i 's/==/~=/g' env-chilly/$DEPLOYMENT_NAME/requirements.txt