#!/usr/bin/env python

import os
import subprocess
import boto3


env = os.environ.get('ENVIRONMENT', None)
admin_arn = os.environ.get('ADMIN_ARN', None)
central_ecr_account_id = os.environ.get('CENTRAL_ECR_ACCOUNT_ID', None)
deployment_name = os.environ.get('DEPLOYMENT_NAME', None)

# TODO: make sure all these env vars are not None


# REMOVE!
#env = 'dev'

promotions = {
   'dev': 'test',
   'test': 'prod'
}

ecr = boto3.client('ecr')

response = ecr.batch_get_image(
    repositoryName=deployment_name,
    registryId=central_ecr_account_id,
    imageIds=[
        {
            'imageTag': f'latest-{env}'
        },
    ],
    acceptedMediaTypes=[
        'string',
    ]
)

manifest = response['images'][0]['imageManifest']

response = ecr.put_image(
    repositoryName=deployment_name,
    registryId=central_ecr_account_id,
    imageManifest=manifest,
    imageTag=f'latest-{promotions[env]}'
)
