#! /bin/bash

# deletes ECR images simply

set -eu

if [[ "$#" == "0" ]]; then
    echo "usage: image-delete  [--untagged] <tag-or-ecr-digest>..."
fi

if [[ $1 == "--untagged" ]]; then
    IMAGES=$(awsudo ${ADMIN_ARN} aws ecr list-images --registry-id $ECR_ACCOUNT_ID --repo tike --output text | awk --field-separator=" " 'NF==2 { print $2; }')
else
    IMAGES=$*
fi

for image in ${IMAGES}; do
    if [[ `echo $image | cut -d':' -f1` == "sha256" ]]; then
       QUALIFIER=imageDigest
    else
	QUALIFIER=imageTag
    fi
    awsudo ${ADMIN_ARN} aws ecr batch-delete-image --registry-id ${ECR_ACCOUNT_ID} --repository-name ${IMAGE_REPO} --image-ids ${QUALIFIER}=${image}
done

