#! /bin/bash

set -eu

#     usage:  image-cp   <path-inside-container>   [<path-on-host> or PWD]
#
#     Copy the specified filepath out of the currently configured image
#     to the specified location on the host or the PWD.   This version is
#     limited to single files which can be cat'ed out of Docker.

PATH_TO_EXPORT=$1
WHERE_TO_PUT_IT=${2:-`pwd`}

CONTAINER=$(docker run --rm -d ${IMAGE_ID} /bin/sleep 14400)

docker cp ${CONTAINER}:${PATH_TO_EXPORT}  ${WHERE_TO_PUT_IT}

docker container stop ${CONTAINER}  >& /dev/null
