#! /bin/bash -e

set -u

# Update the configured deployment based on files stored in the commmon
# deployment.

cd ${IMAGE_DIR}

# -------------------------------------------------------------------------
# Update TLS cert in "common" image directory to CI-node's cert.  This cert
# enables TLS/SSL to work inside the Docker build process which tunnels through
# the host OS without decryption, but must be decrypted for the STScI firewall
# to do packet inspection before continuing on to package distribution sites.
#
# This cert bundle should work anywhere enabling the same image to work inside
# and outside AWS networks.

if [ -f "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem" ]; then
   cp -f /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem ../../common/image
fi

# -------------------------------------------------------------------------
# Ideally mission images are defined by a Dockerfile created from two parts
# which are concatenated:
#
# 1. Dockerfile.custom in the mission image directory.
#
# 2. Dockerfile.trailer from the common image directory.
#
# If no Dockerfile.custom is defined,  assume the mission has opted out of
# the standard approach for using the common base image and leave the
# Dockerfile alone.
#
#
if [[ -f Dockerfile.custom ]]; then
   # Combine Dockerfile.custom with the common "trailer" to create Dockerfile
   cat Dockerfile.custom ../../common/image/Dockerfile.trailer >Dockerfile
fi

# -------------------------------------------------------------------------
# If a prior build updated environment xxx-frozen.yml files,  they become
# Docker cache busters since they must be copied into the image prior to
# building the related environment. To avoid busting,  clear all changes to
# the xxx-frozen.yml files prior to starting any un-frozen build;  they'll
# be automatically recreated anyway and don't contribute until USE_FROZEN=1.

if [[ $USE_FROZEN == "0" ]]; then
  # echo "Clearing frozen image specs to avoid Docker cache busting."
  # echo "Add or commit them to git prior to unfrozen builds to avoid this clear."
  git checkout -- environments/frozen
  git checkout -- ../../common/image/environments/frozen
fi
