#! /usr/bin/env python
#
# Based on ACCOUNT_ID and DEPLOYMENT_NAME environment settings, get credentials
# associated with assuming a secrets repo setup role and print them out as bash
# export statements which can be sourced into a shell script.
#
import os
import subprocess
import ast

account = os.environ["ACCOUNT_ID"]
cluster = os.environ["DEPLOYMENT_NAME"]
admin_arn = os.environ["ADMIN_ARN"]

output = subprocess.check_output(
    f"aws sts assume-role --role-arn {admin_arn} --role-session-name clone".split(),
    text=True,
)

values = ast.literal_eval(output)

key = values["Credentials"]["AccessKeyId"]
secret = values["Credentials"]["SecretAccessKey"]
token = values["Credentials"]["SessionToken"]

print(f"export AWS_ACCESS_KEY_ID={key}")
print(f"export AWS_SECRET_ACCESS_KEY={secret}")
print(f"export AWS_SESSION_TOKEN={token}")
