#! /bin/bash -u

# Push the secrets repo back up to the codecommit repository

cd ${JUPYTERHUB_DIR}/secrets/deployments/${DEPLOYMENT_NAME}/secrets

awsudo arn:aws:iam::${ACCOUNT_ID}:role/${DEPLOYMENT_NAME}-secrets-repo-setup git push
