#! /bin/bash -eu

# Edit the decrypted secrets file associated with this deployment and environment,
# e.g. staging.yaml,  using sops.   Re-encrypt the edited file,  add it to git,
# and commit it.

secrets_file=${ENVIRONMENT}.yaml

cd ${JUPYTERHUB_DIR}/deployments/${DEPLOYMENT_NAME}/secrets

awsudo $ADMIN_ARN sops $secrets_file

git add $secrets_file
git commit
