#! /bin/bash -u

# Clone the codecommit secrets repo created by terraform-deploy for
# this deployment.

cd ${JUPYTERHUB_DIR}

cd deployments/$DEPLOYMENT_NAME

# Define AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_SESSION_TOKEN in the
# environment.  First get export commands, then eval exports.
exports=$(secrets-get-exports)
eval ${exports}

git config --global credential.helper '!aws codecommit credential-helper $@'
git config --global credential.UseHttpPath true
git clone https://git-codecommit.us-east-1.amazonaws.com/v1/repos/$DEPLOYMENT_NAME-secrets secrets

# NOTE: using this script is now the recommended method, so no need to print this message
#cd secrets
#if  [[ ! -f .sops.yaml ]]; then
#    echo "TODO: .sops.yaml is missing.  Follow the steps in the documentation for obtaining and/or"
#    echo "updating .sops.yaml and add it to git at `pwd`/.sops.yaml"
#fi
