#! /bin/bash

# This script reduces image size by replacing redundant files in the image with
# a hard link to a master copy, nominally anything under /opt/conda.  The hard
# linked image is exported and re-imported in order to squash the file system.

# If "docker build --squash" ever becomes available, this script can
# essentially be replaced by moving the cross-linking step into
# Dockerfile.trailer and then just using "docker build --squash" to replace the
# export/import.

set -eu

IMG=${1:-${IMAGE_ID}}
EXPORT_FILE=${2:-${IMG}.export}
REPO=`echo $IMG | cut -d':' -f1`

# --------------------------------------------------------------------------
# First run the crosslink tool to eliminate redundant files using hard links

echo "----------------------------------------------------------------------"
time squash-crosslink ${IMG}
docker image tag $IMG ${REPO}:crosslinked
echo "Crosslinking...  retagging cross-linked image ${REPO}:crosslinked as ${IMG}..."

# --------------------------------------------------------------------------
# Export the net file system to eliminate intermediate layers and redundancy

echo "----------------------------------------------------------------------"
echo "Exporting crosslinked file system..."
time squash-export   ${IMG}  ${EXPORT_FILE}

# --------------------------------------------------------------------------
# Import the net file system into a new smaller image with just one layer

echo "----------------------------------------------------------------------"
echo "Re-importing crosslinked file system...  retagging squashed image as ${IMG}..."
time squash-import   ${IMG} ${EXPORT_FILE}
docker image tag ${REPO}:squashed   ${IMG}

rm ${EXPORT_FILE}

echo "----------------------------------------------------------------------"
echo "Current docker image listing..."
docker image ls
