#! /usr/bin/env bash

# Run code quality tool flake8 on all python sources which can be found

cd $JUPYTERHUB_DIR

echo "flake8 version:"  `flake8 --version`

flake8  --max-line-length 120  --count  --statistics  --ignore W291,W503 `sscan-find-python-files`
