#! /usr/bin/env bash

set -eu

# Run security scanner "bandit" on all python sources which can be found
# MEDIUM level and confidence,  or greater.
bandit -v -ll -ii --format txt `sscan-find-python-files`
