#! /bin/bash -u

cd $JUPYTERHUB_DIR

echo "====================================================="
echo "Checking YAML files for loadability                  "
echo "====================================================="
sscan-yaml `find deployments tools -name '*.yaml' -o -name '*.yml'`
yaml_status=$?

echo "====================================================="
echo "Scanning source code for quality with flake8         "
echo "====================================================="
sscan-flake8
flake8_status=$?

echo "====================================================="
echo "Scanning source code for vulnerabilities using bandit"
echo "====================================================="
sscan-bandit
bandit_status=$?

echo "====================================================="
echo "Scanning environment dependencies using safety       "
echo "====================================================="
sscan-safety
safety_status=$?

fail=`expr $yaml_status + $flake8_status + $bandit_status + $safety_status`
exit $fail
