#! /usr/bin/env bash

cd $JUPYTERHUB_DIR

# Run safety on jupyterhub-deploy requirements.txt and deployment
# frozen specs to check package dependencies for security issues.

pip list --format=freeze >/tmp/requirements.txt

sscan-run-safety /tmp/requirements.txt

sscan-run-safety  `sscan-find-frozen-specs`
