#! /usr/bin/env bash

# Run code quality tool flake8 on all python sources which can be found

cd $JUPYTERHUB_DIR

flake8  --max-line-length 120  --ignore E203,W503,W504 --count  --statistics  `sscan-find-python-files`

# E203  whitespace before :,  Black passed it
