jupyterhub:
  hub:
    pdb:
      enabled: true
      minAvailable: 0
    extraConfig:
      spawning: |
        c.KubeSpawner.start_timeout = 15 * 60  # Up to 15 minutes
    extraFiles:
      announcements_service:
        mountPath: /usr/share/jupyterhub/announcements.py
    extraVolumes:
      - name: quota-control
        persistentVolumeClaim:
          claimName: quota-control-jh-pvc
    extraVolumeMounts:
      - name: quota-control
        mountPath: "/announcements"
        subPath: "announcements"
  proxy:
    chp:
      pdb:
        enabled: true
        minAvailable: 0
  singleuser:
    storage:
      type: "static"
      static:
        pvcName: "users-jh-pvc"
        subPath: "{username}"
      extraVolumes:
        - name: quota-control
          persistentVolumeClaim:
            claimName: quota-control-jh-pvc
      extraVolumeMounts:
        - name: quota-control
          mountPath: "/quota-control"
          subPath: "{username}"
          readOnly: true
    defaultUrl: "/lab"
  scheduling:
    userScheduler:
      enabled: true
      pdb:
        enabled: true
    corePods:
      nodeAffinity:
        matchNodePurpose: require
    userPods:
      nodeAffinity:
        matchNodePurpose: require
    podPriority:
      enabled: true
      globalDefault: true
      defaultPriority: 10
      userPlaceholderPriority: 0
