jupyterhub:
  hub:
    pdb:
      enabled: true
      minAvailable: 0
    extraConfig:
      spawning: |
        c.KubeSpawner.start_timeout = 15 * 60  # Up to 15 minutes
      get_email: |
        def get_email(response):
            return response['attrib']['email']
      set_username_key: |
          c.GenericOAuthenticator.username_key = get_email
  proxy:
    chp:
      pdb:
        enabled: true
        minAvailable: 0
  singleuser:
    storage:
      dynamic:
        storageClass: "aws-efs"
    defaultUrl: "/lab"
  scheduling:
    userScheduler:
      enabled: true
      pdb:
        enabled: true
        minAvailable: 0
    corePods:
      nodeAffinity:
        matchNodePurpose: require
    userPods:
      nodeAffinity:
        matchNodePurpose: require
    podPriority:
      enabled: true
      globalDefault: true
      defaultPriority: 10
      userPlaceholderPriority: 0
